### ISSUE TITLE
Alias for a function is at wrong location

### ISSUE THREAD

**Issue by vbansal22** [lfittl/pg_query_go#20]
Parse this simple query

SELECT COUNT(OrderID) AS ord FROM SalesOrders

You will see that the location for the ord alias and the function COUNT(OrderID) is the same -- location 7. This prevents its use with databases where case sensitivity of column, table, function or alias names is important. Basically it is not possible to reconstitute the statement by traversing the AST because offsets to the names in the query to restore actual names would be incorrect.  Could a fix be provided? Thanks

`"ResTarget": {
"name": "ord",
"val": {
"FuncCall": {
"funcname": [
{
"String": {
"str": "count"
}
}
],
"args": [
{
"ColumnRef": {
"fields": [
{
"String": {
"str": "orderid"
}
}
],
"location": 13
}
}
],
"location": 7
}
},
"location": 7
}`

**Comment by lfittl** [comment]
Hi @vbansal22!

Thanks for reaching out - this is likely a limitation in the Postgres parser itself, since it doesn't store the location precisely enough.

Therefore, its not really feasible to provide a fix, since we try to stay close to upstream. If you'd like to debug this more closely, I'd encourage you to investigate the C code for this in https://github.com/lfittl/libpg_query (and the Postgres source its based on)

I'll close this for now, since there isn't anything that can be fixed here on the Go library itself.
